AWSTemplateFormatVersion: 2010-09-09
	Description: >-
	  This stack holds and exports various parameters which control
	  the deployment of other resources associated with the JupyterHub
	  stack. It should be created manually before any other stacks
	  and allows the rest of the templates to match between test and 
	  production accounts.
	
	Parameters:
	

	  BootstrapBucketName:
	    Description: Bucket name for FW bootstrap configuration
	    Default: firewall001.cma.gov.uk
	    Type: String
	    
	  DataLakeBucketName:
	    Description: Bucket name for the Datalake.
	    Default: datalake.cma.gov.uk
	    Type: String
	    
	  CloudFormationBucketName:
	    Description: Bucket name for CloudFormation templates.
	    Default: cloudformation.cma.gov.uk
	    Type: String
	

	  VPCCIDRBlock:
	    Description: CIDR block for the JupyterHub VPC.
	    Default: 10.222.0.0/16
	    Type: String
	

	  PublicSubnetCIDRBlock:
	    Description: CIDR block for the Public (FW) subnet.
	    Default: 10.222.0.0/24
	    Type: String
	    
	  FWManagementNetworkInterfaceAddress:
	    Description: Private address for the FW management interface.
	    Default: 10.222.0.99
	    Type: String
	    
	  FWPublicNetworkInterfaceAddress:
	    Description: Private address for the FW public network interface.
	    Default: 10.222.0.100
	    Type: String
	    
	  HubSubnetCIDRBlock:
	    Description: CIDR block for the Hub subnet.
	    Default: 10.222.1.0/24
	    Type: String
	

	  FWPrivate12NetworkInterfaceAddress:
	    Description: Private address for the FW Hub network interface.
	    Default: 10.222.1.11
	    Type: String
	    
	  HubPrivateIPAddress:
	    Description: Private IP address for the Hub.
	    Default: 10.222.1.101
	    Type: String
	

	  ServerSubnetCIDRBlock:
	    Description: CIDR block for the Server subnet.
	    Default: 10.222.2.0/24
	    Type: String
	    
	  FWPrivate13NetworkInterfaceAddress:
	    Description: Private address for the FW Server network interface.
	    Default: 10.222.2.11
	    Type: String
	

	  PrimaryEFSID:
	    Description: Primary Elastic FileSystem ID
	    Default: fs-2e4fb8df
	    Type: String
	    
	  SecondaryEFSID:
	    Description: Secondary (backup) Elastic FileSystem ID
	    Default: fs-6a29df9b
	    Type: String
	

	  FWEIPAllocation:
	    Description: EIP Allocation ID for the firewall
	    Default: eipalloc-00743a5e583bca82b
	    Type: String
	    
	  FWElasticIP:
	    Description: >- 
	      Elastic IP address for the firewall management interface.
	    Default: 35.178.39.244
	    Type: String
	

	  HubEIPAllocation:
	    Description: EIP Allocation for the Hub
	    Default: eipalloc-0dc1aef661ff4d360
	    Type: String
	

	  HubElasticIP:
	    Description: >-
	      Elastic IP address for the JupyterHub interface.
	    Default: 3.9.27.157
	    Type: String
	

	  ServerKeyName:
	    Description: >-
	      Name of an existing EC2 KeyPair to enable SSH access instances
	      associated with this stacl (Hint: You MUST have its private key)
	    Default: jupyterhub
	    Type: 'AWS::EC2::KeyPair::KeyName'
	    
	  IngressIPAddressRange:
	    Description: Allow ingress from this IP address range.
	    Default: 86.12.161.20/32
	    Type: String
	    
	Conditions:
	  HasNot: !Equals [ 'true', 'false' ]    
	    
	# dummy (null) resource, never created
	Resources:
	  NullResource:
	    Type: 'Custom::NullResource'
	    Condition: HasNot    
	    
	Outputs:
	      
	  BootstrapBucketName:
	    Description: Bucket name for FW bootstrap configuration
	    Value: !Ref BootstrapBucketName
	    Export:
	      Name: JupyterHub-BootstrapBucketName
	    
	  DataLakeBucketName:
	    Description: Bucket name for the Datalake.
	    Value: !Ref DataLakeBucketName
	    Export:
	      Name: JupyterHub-DataLakeBucketName
	    
	  CloudFormationBucketName:
	    Description: Bucket name for CloudFormation templates.
	    Value: !Ref CloudFormationBucketName
	    Export:
	      Name: JupyterHub-CloudFormationBucketName
	

	  VPCCIDRBlock:
	    Description: CIDR block for the JupyterHub VPC.
	    Value: !Ref VPCCIDRBlock
	    Export:
	      Name: JupyterHub-VPCCIDRBlock
	

	  PublicSubnetCIDRBlock:
	    Description: CIDR block for the Public (FW) subnet.
	    Value: !Ref PublicSubnetCIDRBlock
	    Export:
	      Name: JupyterHub-PublicSubnetCIDRBlock
	    
	  FWManagementNetworkInterfaceAddress:
	    Description: Private address for the FW management interface.
	    Value: !Ref FWManagementNetworkInterfaceAddress
	    Export:
	      Name: JupyterHub-FWManagementNetworkInterfaceAddress
	    
	  FWPublicNetworkInterfaceAddress:
	    Description: Private address for the FW public network interface.
	    Value: !Ref FWPublicNetworkInterfaceAddress
	    Export:
	      Name: JupyterHub-FWPublicNetworkInterfaceAddress
	    
	  HubSubnetCIDRBlock:
	    Description: CIDR block for the Hub subnet.
	    Value: !Ref HubSubnetCIDRBlock
	    Export:
	      Name: JupyterHub-HubSubnetCIDRBlock
	

	  FWPrivate12NetworkInterfaceAddress:
	    Description: Private address for the FW Hub network interface.
	    Value: !Ref FWPrivate12NetworkInterfaceAddress
	    Export:
	      Name: JupyterHub-FWPrivate12NetworkInterfaceAddress
	

	  HubPrivateIPAddress:
	    Description: Private IP address for the Hub.
	    Value: !Ref HubPrivateIPAddress
	    Export:
	      Name: JupyterHub-HubPrivateIPAddress
	

	  ServerSubnetCIDRBlock:
	    Description: CIDR block for the Server subnet.
	    Value: !Ref ServerSubnetCIDRBlock
	    Export:
	      Name: JupyterHub-ServerSubnetCIDRBlock
	    
	  FWPrivate13NetworkInterfaceAddress:
	    Description: Private address for the FW Server network interface.
	    Value: !Ref FWPrivate13NetworkInterfaceAddress
	    Export:
	      Name: JupyterHub-FWPrivate13NetworkInterfaceAddress
	

	  PrimaryEFSID:
	    Description: Primary Elastic FileSystem ID
	    Value: !Ref PrimaryEFSID
	    Export:
	      Name: JupyterHub-EFS-Primary
	    
	  SecondaryEFSID:
	    Description: Secondary (backup) Elastic FileSystem ID
	    Value: !Ref SecondaryEFSID
	    Export:
	      Name: JupyterHub-EFS-Secondary
	

	  FWEIPAllocation:
	    Description: EIP Allocation ID for the firewall
	    Value: !Ref FWEIPAllocation
	    Export:
	      Name: JupyterHub-FWEIPAllocation
	    
	  FWElasticIP:
	    Description: >- 
	      Elastic IP address for the firewall management interface.
	    Value: !Ref FWElasticIP
	    Export:
	      Name: JupyterHub-FWElasticIP
	

	  HubEIPAllocation:
	    Description: EIP Allocation for the Hub
	    Value: !Ref HubEIPAllocation
	    Export:
	      Name: JupyterHub-HubEIPAllocation
	

	  HubElasticIP:
	    Description: >-
	      Elastic IP address for the JupyterHub interface.
	    Value: !Ref HubElasticIP
	    Export:
	      Name: JupyterHub-HubElasticIP
	

	  ServerKeyName:
	    Description: >-
	      Name of an existing EC2 KeyPair to enable SSH access instances
	      associated with this stacl (Hint: You MUST have its private key)
	    Value: !Ref ServerKeyName
	    Export:
	      Name: JupyterHub-ServerKeyName
	    
	  IngressIPAddressRange:
	    Description: Allow ingress from this IP address range.
	    Value: !Ref IngressIPAddressRange
	    Export:
	      Name: JupyterHub-IngressIPAddressRange

