AWSTemplateFormatVersion: "2010-09-09"
	

	Description: >
	  This stack creates build jobs to enable CI for 
	  the jupyterhub stack.
	  
	Resources:
	  
	  CodeBuildServiceRole:
	    Type: AWS::IAM::Role
	    Properties:
	      RoleName: !Sub JupyterHub-Builder
	      AssumeRolePolicyDocument:
	        Version: "2012-10-17"
	        Statement:
	          -
	            Effect: "Allow"
	            Principal:
	              Service:
	                - "codebuild.amazonaws.com"
	            Action:
	              - "sts:AssumeRole"
	      Path: /service-role/
	      Policies:
	        -
	          PolicyName: "CodeBuildAccessPolicies"
	          PolicyDocument:
	            Version: "2012-10-17"
	            Statement:
	              -
	                Effect: "Allow"
	                Action:
	                  - '*'
	                Resource:
	                  - '*'
	

	  CodeBuildProject:
	    Type: AWS::CodeBuild::Project
	    Properties:
	      Name: JupyterHub-S3Sync-UsersUpdate
	      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
	      Artifacts:
	        Type: no_artifacts
	      Environment:
	        Type: LINUX_CONTAINER
	        ComputeType: BUILD_GENERAL1_SMALL
	        Image: aws/codebuild/standard:2.0
	      Source:
	        Auth:
	          Type: OAUTH
	        Location: https://github.com/cmagovuk/jupyterhub-cloudformation.git
	        Type: GITHUB
	        BuildSpec: build/buildspec.yml
	      Triggers:
	        Webhook: true
	        FilterGroups:
	          - - Type: EVENT
	              Pattern: PUSH
	            - Type: HEAD_REF
	              Pattern: '^refs/heads/master$'
	      TimeoutInMinutes: 10
	      VpcConfig:
	        SecurityGroupIds: 
	          - !ImportValue JupyterHub-Build-SecurityGroup-NoIngress
	        Subnets: 
	          - !ImportValue JupyterHub-Build-Subnet-Private
	        VpcId: !ImportValue JupyterHub-Build-VPC
	        
	  CodeBuildProject2:
	    Type: AWS::CodeBuild::Project
	    Properties:
	      Name: JupyterHub-HubImageBuild
	      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
	      Artifacts:
	        Type: no_artifacts
	      Environment:
	        Type: LINUX_CONTAINER
	        ComputeType: BUILD_GENERAL1_SMALL
	        Image: aws/codebuild/standard:2.0
	        PrivilegedMode: true
	        EnvironmentVariables:
	          - Name: AccountId
	            Value: !Sub ${AWS::AccountId}
	            Type: PLAINTEXT
	      Source:
	        Auth:
	          Type: OAUTH
	        Location: https://github.com/cmagovuk/jupyterhub-hub-image.git
	        Type: GITHUB
	        BuildSpec: buildspec.yaml
	      Triggers:
	        Webhook: true
	        FilterGroups:
	          - - Type: EVENT
	              Pattern: PUSH
	            - Type: HEAD_REF
	              Pattern: '^refs/heads/master$'
	      TimeoutInMinutes: 10
	      VpcConfig:
	        SecurityGroupIds: 
	          - !ImportValue JupyterHub-Build-SecurityGroup-NoIngress
	        Subnets: 
	          - !ImportValue JupyterHub-Build-Subnet-Private
	        VpcId: !ImportValue JupyterHub-Build-VPC
